# Generated by Django 2.2.1 on 2019-11-19 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='First Name', max_length=30)),
                ('lastname', models.CharField(default='Last Name', max_length=30)),
                ('profile_intro', models.TextField(default='Default intro. Change this to tell other users a little more about yourself')),
                ('image', models.ImageField(default='user-default.jpg', upload_to='user_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
